// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineCordobaWebApi.Models;

public partial class Factura
{
    public int NroFactura { get; set; }

    public int? IdCliente { get; set; }

    public DateTime? FechaCompra { get; set; }

    public int? IdFormaPago { get; set; }

    public int? IdBoleteria { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual Boleteria IdBoleteriaNavigation { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}