// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineCordobaWebApi.Models;

public partial class Lenguaje
{
    public int IdLenguaje { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();
}