// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineCordobaWebApi.Models;

public partial class Pelicula
{
    public int IdPelicula { get; set; }

    public string TituloPelicula { get; set; }

    public int? DuracionMin { get; set; }

    public int? IdClasificacion { get; set; }

    public int? IdPais { get; set; }

    public int? IdDirector { get; set; }

    public int? IdEstado { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual ICollection<GenerosPelicula> GenerosPeliculas { get; set; } = new List<GenerosPelicula>();

    public virtual Clasificacione IdClasificacionNavigation { get; set; }

    public virtual Directore IdDirectorNavigation { get; set; }

    public virtual TiposEstado IdEstadoNavigation { get; set; }

    public virtual Paise IdPaisNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}