// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineCordobaWebApi.Models;

public partial class Promocione
{
    public int IdPromocion { get; set; }

    public int? IdFuncion { get; set; }

    public string Descripcion { get; set; }

    public decimal? Porcentaje { get; set; }

    public string DiasAplicados { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }
}