// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineCordobaWebApi.Models;

public partial class Reserva
{
    public int IdReserva { get; set; }

    public int? IdCliente { get; set; }

    public int? IdFuncion { get; set; }

    public int? IdButacaSala { get; set; }

    public DateTime? FechaReserva { get; set; }

    public TimeSpan? HoraReserva { get; set; }

    public int? IdEstadoReserva { get; set; }

    public virtual ButacasSala IdButacaSalaNavigation { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual EstadosReserva IdEstadoReservaNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }
}