// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineCordobaWebApi.Models;

public partial class Sala
{
    public int IdSala { get; set; }

    public string NombreSala { get; set; }

    public int? IdTipoSala { get; set; }

    public int? Capacidad { get; set; }

    public virtual ICollection<ButacasSala> ButacasSalas { get; set; } = new List<ButacasSala>();

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual TiposSala IdTipoSalaNavigation { get; set; }
}