// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineCordobaWebApi.Models;

public partial class Ticket
{
    public int NroTicket { get; set; }

    public int? IdButacaSala { get; set; }

    public int? IdPelicula { get; set; }

    public DateTime? Fecha { get; set; }

    public TimeSpan? Hora { get; set; }

    public decimal? Precio { get; set; }

    public int? NroFactura { get; set; }

    public int? IdFuncion { get; set; }

    public virtual ButacasSala IdButacaSalaNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}